Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,8 +22,13 @@ jobs:
           node fetch-webflow.js
       - name: Commit and Push
         run: |
-          git config --global user.name 'GitHub Action'
-          git config --global user.email 'action@github.com'
-          git add data.json
-          git commit -m "Update data" || exit 0
-          git push
+          if [ -f data.json ]; then
+            git config --global user.name 'GitHub Action'
+            git config --global user.email 'action@github.com'
+            git add data.json
+            git commit -m "Update data"
+            git push
+          else
+            echo "data.json not found, skipping commit"
+            exit 1
+          fi
